angelics
youknowone/Evolve pull request #5
Opened 2023-07-30 10:12 UTC by youknowone

2023-07-30 15:06 UTC, garygruener requested changes

2023-07-30 15:06 UTC, garygruener commented on strings/strings.ko-KR.json
> +  "race_cherub_home": "심장",
종족마다 행성 이름이나 총독 이름 같은 걸 그대로 직역하니 이상하게 느껴지는 것도 많더라고요. (예시로 육식동물 문명의 총독 이름 중 하나가 '킁킁'으로, 극지 종족의 이름 중 하나인 Coldfoot이 '수족냉증' 이라고 나옵니다.) 저는 가장 단순하게 그냥 음차하기 (Paws를 '포'로, sniff를 '스니프'로)같은 걸 생각했는데, 이 문제를 어떻게 해결하는 게 좋을까요...? ['kettle'이라는 이름](https://en.wikipedia.org/wiki/Kettle_(surname))도 '주전자'라고 번역된 것을 보면 오역인 것 같습니다. 저도 어찌할 바 몰라 이번 크툴루 종족 같은 경우도 그냥 단어를 번역해놓고 놔뒀네요.

2023-07-30 15:28 UTC, youknowone commented on strings/strings.ko-KR.json
> +  "race_cherub_home": "심장",
한 눈에 보이는 단어들끼리 일관성을 갖추면 된다고 생각하는데, 이 경우는 모든 행성이 번역된 이름처럼 보여서 이정도로 잘 맞는거 같습니다.

텍스트 게임이니 텍스트가 게임의 분위기와 유머를 잘 전달해 줘야하는데, 음차는 보통 음차한 단어를 보고 원래 단어가 뭔지도 알아야 하고 그 단어의 뜻도 알아야해서, 고유명사를 번역할땐 괜찮지만 단어의 뜻이 전하는 의미나 분위기가 있는 경우는 가능한 피하는게 좋은것 같습니다. 저라면 'Paws'는 절대 '포'라고 하지 않을것 같네요.
총독 이름은 '킁킁'은 괜찮고 '수족냉증'은 안좋다고 생각해요. 톨킨 세계관이라면 '차가운발'이 올바른 번역이겠지요.

하나씩 고치면 되지 않을까 생각합니다 😄

2023-07-30 16:27 UTC, garygruener commented on strings/strings.ko-KR.json
> +  "race_cherub_home": "심장",
가장 좋은 방법이네요. 앞서 말씀드렸던 kettle → 주전자 같은 경우는 인간형에서 보이는 것 같은데 이런 경우는 그냥 고유명사 취급해서 하나씩 맞게 바꿔나가는 게 좋을 것 같습니다.

2023-08-20 19:23 UTC, youknowone commented on strings/strings.ko-KR.json
> +  "race_cherub_home": "심장",
새 패치에 들어갔는데 이게 빠져서 들어갔습니다 ㅜㅜ

2023-08-29 11:07 UTC, youknowone commented on strings/strings.ko-KR.json
> +  "race_cherub_home": "심장",
괜찮으시면 ok사인 주시면 머지하겠습니다 😄

2023-08-31 13:52 UTC, merged